name: multipul job workflow

on:
  workflow_dispatch:

  # THIS ENV VARS ARE AVAILABLE TO ALL JOBS IN THIS WORKFLOW
env:
  NODE_ENV: production
  APP_NAME: practice_app

jobs:
  first-job-workflow:
    runs-on: ubuntu-latest
    # here we can define env vars for this job only, these env vars are not available to other jobs in this workflow
    env:
      FIRST_JOB_ENV: this is first job env var
    steps:
      - name: first step
        env:
          FIRST_STEP_ENV: this is first step env var
        run: echo ${FIRST_STEP_ENV}

  second-job-workflow:
    runs-on: ubuntu-latest
    needs: [first-job-workflow]

    steps:
      - name: second step
        run: echo "this is second multuple workflow"

  third-job-workflow:
    runs-on: ubuntu-latest
    needs: [first-job-workflow, second-job-workflow]

    steps:
      - name: third step
        run: echo "this is third multiple workflow"
